#ifndef STREVAL_PARSING_ERROR_H
#define STREVAL_PARSING_ERROR_H

enum parsing_error {
    LEFT_MISSING = 0,
    OP_EXPECTED = 1,
    RIGHT_MISSING = 2,
    INVALID_CHAR = 3,
    UNKNOWN_FUNC = 4,
    UNKNOWN_CONST = 5,
    INVALID_NUMBER_FORMAT = 6,
    UNEXPECTED_PARENTHESIS = 7,
    UNCLOSED_PARENTHESIS = 8
};

#endif //STREVAL_PARSING_ERROR_H
